# Generated by Django 3.2.5 on 2022-04-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.account.staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=modules.account.staff.models.img_dest)),
                ('full_name', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(2, 'Không xác định'), (0, 'Nam'), (1, 'Nữ')])),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'db_table': 'staffs',
                'ordering': ['-id'],
            },
        ),
    ]
